### ISSUE TITLE
using type 'built' with --layer-type=squashfs fails

### ISSUE THREAD

**Issue by smoser** [anuvu/stacker#115]
I'm trying to do something like the following, and it is failing, with a message like:

    error: no descriptor found for reference "base"
    Error initializing source oci:/home/smoser/workdir/stacker/test.d/oci:base

stacker is v0.5.0-297-g3755182.  Using --layer-type=tar works fine. Here is my stacker.yaml.

```yaml
base:
  from:
    type: tar
    url: root.tar.gz
  run: |
    echo "hello world" > /message

myroot:
  from:
    type: built
    tag: base
  run: |
    echo "foo bar" > /message

```

I'm running with [build.sh](https://github.com/anuvu/stacker/files/5804185/build.sh.txt), which just downloads a root.tar.gz, and then invokes stacker clean and stacker build.

Here is full output of build.sh: [build-squashfs.log](https://github.com/anuvu/stacker/files/5804193/build-squashfs.log)
