### ISSUE TITLE
allow specifying hash of import source

### ISSUE THREAD

**Issue by mikemccracken** [anuvu/stacker#119]
for import entries, allow specifying the hash so that stacker can check that the bits you get are the bits you want

something like this

```yaml
first:
    from:
        type: docker
        url: docker://centos:latest
    import:
        - path: "config.json"
          hash: "BEEFcafeaaaaAAAA...."
```

RFC: maybe also add a flag to have stacker reject any stackerfiles that have imports with no hash?

**Comment by tych0** [comment]
The only thing I'd suggest is to make sure it works with a nicer yaml syntax:

```
import:
    - path: "config.json"
      hash: "BEEFcafeaaaaAAAA...."
````
But IIUC that should be equivalent to what you wrote.

**Comment by mikemccracken** [comment]
> But IIUC that should be equivalent to what you wrote.

yes that's the same structure, and the parser should accept either - I just couldn't remember what the nicer syntax for "list of dicts" was :)

**Comment by mikemccracken** [comment]
ah, to be clearer - tycho's example is the better syntax (even though it's equivalent) and IMO we should pretend the inline dict version doesn't exist :)

I'm going to update the summary

**Comment by tych0** [comment]
+1

**Comment by peusebiu** [comment]
Hello, 

Do you want to specify hash for all imports types: files/urls/previously built layers files?
Also, this change should be backwards compatible and stacker should supported both imports type, even both combined in the same stacker file, right?

The user should be able to do something like this:

```
  import:
    - path: test.txt
      hash: d8c97d4b881519d12a5c8defa61d6b2b0bf8b3ddcf9cb0ce6e544bbde19afd7f
    - stacker://first/example.txt
 ```
