### ISSUE TITLE
introduce a mechanism for testing built layers

### ISSUE THREAD

**Issue by tych0** [anuvu/stacker#149]
Stacker builds stuff, and it is reasonable for people to want stacker to run basic smoke tests on the stuff it built. Consider the following example:

```
foo:
    from:
        type: docker
        url: docker://ubuntu:latest
    import:
        - install_foo.sh
        - test_foo.sh
    run: |
        /stacker/install_foo.sh
    test: |
        # suppose install_foo.sh installs a foo service; this service can bind to 0.0.0.0 as long as it
        # chooses a port > 1024. it can also announce itself to an existing cluster somewhere else, etc.
        /usr/sbin/foo --background --port 50000
        # now we can run some basic smoke tests against foo
        /stacker/test_foo.sh 50000
```
        
A few notes about the test environment:

* Anything in test's rootfs is ephemeral
* /stacker is available with the same imports/binds as in build
* test uses host's netns as build does

How to run it:

* `stacker test` would first build the layers if necessary, then run the tests. If any of the tests exit(1), it exit(1)s (should we do more fancy things like running *all* the tests and swallowing output unless they fail?)
* maybe a `stacker build --run-tests` instead?

Open questions:

* What to do about the OCI entrypoint if declared? Should we run that in the background and run the test: section as well?

# Pros
* simple to implement + understand

# Cons
* Test coverage can't include stuff which wants custom networking, since stacker just uses the host's netns (we could add a whole new config language for networking, but that seems annoying)
* Same with storage, although we could potentially expose a loopback device over everything in volumes with some heuristics about when to share it across test instances
* Tests will be run serially in the model above, so two containers that need to talk to each other won't be able to (e.g. even if one layer binds to some port > 1024 on the host, a second layer won't be able to connect())
* having to list imports for both testing and

**Comment by smoser** [comment]
> Stacker builds stuff, and it is reasonable for people to want stacker to run
> basic smoke tests on the stuff it built. Consider the following example:

"**basic** smoke tests". emphasis mine.

>  * `stacker test` would first build the layers if necessary, then run the
>  tests. If any of the tests exit(1), it exit(1)s (should we do more fancy
>  things like running _all_ the tests and swallowing output unless they fail?)

"any of the tests"?

You just have one test here.  I do not think that stacker should attempt to understand anything inside the 'test |' blob.  It should just pass that to the `#!` that is present (default to `/bin/sh -e`).

If you did something like:

```yaml
foo:
    from:
       ...
    tests:
        test1: |
           echo this is test one
        test2: |
           echo this is test2  for some reason it always fails
           exit 1
```

So then you can give an error message like the follwoing tests failed: `test2`.
If you want an order, then the easiest thing to do is just use C.sort() order.  Lists have obvious benefits over dictionaries for order, but dictionaries have a built-in name.

>     * maybe a `stacker build --run-tests` instead?

I'd think if there are tests, then you run the tests by default, no?

> Open questions:
> 
>  * What to do about the OCI entrypoint if declared? Should we run that in the
>  background and run the test: section as well?

Next question: If you run it in the background, do you reap it after each individual test?

> # Pros
> 
>  * simple to implement + understand

Agreed.  And it goes a long way.

We are using just differently named '.stacker' files to accomplish this in our containers build.  `stacker recursive-build --stacker-file=stacker.yaml` and then to test with `stacker recursive-build --stacker-file=stacker_test.yaml` or some such.

> # Cons
> 
>  * Test coverage can't include stuff which wants custom networking, since
>    stacker just uses the host's netns (we could add a whole new config language
>    for networking, but that seems annoying)
> 
>  * Same with storage, although we could potentially expose a loopback device
>    over everything in volumes with some heuristics about when to share it
>    across test instances


This is a slippery slope into an container runtime environment.  Once you start inventing a language that sets up custom networking, and runs 2 containers in that networking at the same time and lets them have shared storage.... I think at that point you're pretty much a container runtime.
