### ISSUE TITLE
RFE: support for "output only" builds

### ISSUE THREAD

**Issue by smoser** [anuvu/stacker#183]
Recently in stacker usage, I've been building a lot of "output only" layers.  These containers build something and write its output to /output , and then are used by other layers in an import.

See example stacker.yaml below.  The benefit of this approach is:
 * the 'build-only' layer does not need to be rebuilt when changes are made to layers that use its output.
 * more clear separation of inputs and outputs
 * the runtime container (use-stubby) does not have to have the requirements to build, just to consume.

The notably significant cost of this approach is space.  the cached of 'build-stubby' will contain the whole build filesystem where only the /output are ever needed.  In this example / would be on the order of ~700M (enough for c toolchain) but /output would be on the order of 1M or less.

One potential solution to this would be to allow the layer definition to define `output-dir`.  The layer build process would then remove all other directories after build.  It could potentially do some clever tricks with mounts or tmpfs to avoid a big/slow 'rm' of / at the end of the layer build.

```yaml
build-stubby:
 from:
    type: built
    tag: build
 import:
    - https://github.com/puzzleos/stubby/archive/refs/tags/v1.0.0.tar.gz
 run:
    #!/bin/bash -ex
    mkdir /build
    cd /build
    tar -xvf /stacker/v1.0.0.tar.gz
    cd stubby
    make
    mkdir /output
    tar -cvzf /output/stubby-bin.tar.gz stubby.efi stubby-smash

use-stubby:
  from:
     type: built
     tag: minbase
  import:
     - stacker://build-stubby/output/stubby-bin.tar.gz
  run: |
      #!/bin/bash -ex
      mkdir /stubby
      tar -C /stubby -xf /stacker/stubby-bin.tar.gz
```
