### ISSUE TITLE
stacker build from docker 'setting config item for the container failed'

### ISSUE THREAD

**Issue by toravir** [anuvu/stacker#19]
Am trying to get a stacker build env setup - built the docker based on https://github.com/anuvu/stacker/blob/master/docker/README.md 

I had to add a "RUN go get github.com/containers/skopeo/version" to get to build the docker container. After that a simple stacker yaml (with a run instruction) - i get this error:

`error: run commands failed: failed setting config lxc.execute.cmd to /stacker/.stacker-run.sh: setting config item for the container failed`

My stacker file:
```
first:
    from:
        type: docker
        url: docker://centos:latest
    run: |
        yum -y --nogpgcheck install vim

```
Complete logs:
https://gist.github.com/toravir/3eb56a545008bc3099371d6171a41f91
