### ISSUE TITLE
allow pinning shasum of imports

### ISSUE THREAD

**Issue by mikemccracken** [anuvu/stacker#206]
Motivation: building with a given stackerfile should always produce the same results.

```yaml
import:
  - source: http://$artifactory/place/foo.bin
    dest: /bin/foo
    sha256: 300abcdef...
```

if `sha256` exists, then we check it and fail the build if the source doesn't match it.

we can also add a flag `--remote-input-hash-required` (bad name) that fails the build if any remote imports do not have the `sha256` key. because local imports are likely to be built from the same commit that contains the stacker file, we do not want to force a commit between binary builds and image builds.

we could try to be even smarter about what counts as a local import, where stacker would only count it as local if it's in the same git tree as the stacker file

we could also incorporate #41 along with this since we need to change the syntax anyway
