### ISSUE TITLE
Chained OCI builds may fail due to missing mtree in extracted layers

### ISSUE THREAD

**Issue by CajuM** [anuvu/stacker#40]
Given the following stacker.yaml:
```
t1:
    from:
        type: docker
        url: docker://ubuntu
    run: |
        touch t1

t2:
    from:
        type: oci
        url: ./oci:t1

    run: |
        touch t2

t3:
    from:
        type: oci
        url: ./oci:t2

    run: |
        touch t3
```
t1 will build normaly,
t2 will re-extract t1 into roots/{hash} and build normally
t3 will search for the highest roots/{hash} and find the t1 extracted by t2 which does not have an mtree but has an umoci.json
this will cause an error at https://github.com/anuvu/stacker/blob/master/cmd/umoci.go#L156
perhaps t3 should consider the layer with the highest hash as roots/t2 ?
