### ISSUE TITLE
stacker is caching the import even if when the url changed

### ISSUE THREAD

**Issue by rchamarthy** [anuvu/stacker#55]
Here is a sample stacker file:
```
testwatch:
  from:
    type: docker
    url: docker://aci-docker-reg.cisco.com/${{BASE_IMAGE_REGISTRY:atomix}}/${{BASE_IMAGE_NAME:atom-dev}}:${{BASE_IMAGE_TAG:0.2.14}}
  import:
    - ${{REPO_DIR}}/.build.time
    - http://someplace.come/testwatch/v1.1.1.5a-66-g19323dea/testwatch
...
```
When i use stacker build the first time it fetches the url and caches it. If i change the version in the URL and do stacker build, it does not invalidate the cached copy and fetch the new testwatch copy.

Workaround: stacker clean --all
