### ISSUE TITLE
BUG: fails to rebuild when local OCI "from:" source changes

### ISSUE THREAD

**Issue by pcmoore** [anuvu/stacker#82]
If I have a stacker.yaml file similar to the one below, it doesn't appear to change when the source layer's digest changes.
```
mylayer:
    from:
        type: oci
        url: $OCI_REPO:base
    run: |
        echo "hello world"       
```
