### ISSUE TITLE
BUG: problem with OCI 'from' URLs and build_only layers

### ISSUE THREAD

**Issue by pcmoore** [anuvu/stacker#87]
Given two stacker scripts, "a.yaml" and "b.yaml":
```
% cat a.yaml
a:
  from:
    type: docker
    url: docker://centos:latest
  run: |
        date -R > /a.timestamp
```

```
% cat b.yaml
config:
  prerequisites:
    - ./a.yaml

b-build:
  from:
    type: oci
    url: oci:a
  build_only: true
  run: |
        date -R > /b-build.timestamp

b-final:
  from:
    type: oci
    url: oci:a
  import:
    - stacker://b-build/b-build.timestamp
  run: |
        cat /a.timestamp
        cat /b-build.timestamp
        date -R
```

... if I attempt to build "b.yaml" I run into an error:
```
% stacker build -f b.yaml
... <working build> ...
preparing image b-final...
importing files...
copying /home/pmoore/sources/atomix-swims/tmp/roots/b-build/rootfs/b-build.timestamp
loading oci:oci:a
error: Error initializing source oci:oci:a: no descriptor found for reference "a"
```

For reference, this was seen with stacker version v0.5.0-25-g5c816d1.
