### ISSUE TITLE
provide some way (environment?) to determine if inside a stacker

### ISSUE THREAD

**Issue by smoser** [anuvu/stacker#95]
Our make system is aware of stacker, and will do some things (like write a stacker config) before invoking stacker.
The makefile gets invoked both inside and outside of stacker.

I'd like to have some logic that says "if you're already inside stacker, then you don't need to write a stacker config".

Can we provide some way to allow figure out if you're inside a stacker environment or not ?

maybe something like: STACKER_ENVIRONMENT=the_layer_name

I'd get that right now with the following, but i'd like to not have to define my own STACKER_ENVIRONMENT in the build_env.

```yaml
my_builder:
  from:
    type: docker
    ...
  build_env: {"STACKER_ENVIRONMENT": "my_builder"}
  run: |
    echo hi world. you are in ${STACKER_ENVIRONMENT}
  build_only: true

     

```

**Comment by tych0** [comment]
56eaf93c0b870535373e339679a4356dab373f4c makes it so that STACKER_STACKER_DIR & friends are all exported; is that enough or do you want something more explicit?

**Comment by smoser** [comment]
hm... I don't think anything there is automatic though, right?  You can reference it in the stacker config but I'd have to explicity do that.

I was hoping that this would "just work":

```yaml
my_builder:
  from: ...
  run: |
    echo "you are in the stacker environment ${STACKER_ENVIRONMENT}"
```
